### ISSUE TITLE
Application Error: Slider is not a constructor

### ISSUE THREAD

**Issue by JustinSchneider** [seiyria/bootstrap-slider#671]
I have an application which was previously using Bootstrap Slider version 0.1.7. At latest build, it pulled version 0.1.26, and now chokes out an error "Application Error: Slider is not a constructor" inside Angular.

Anyone else having this issue?

> TypeError: ApplicationErrorSlider is not a constructor
>     at initSlider (http://localhost/stafford/bower_components/angular-bootstrap-slider/slider.js:143:34)
>     at link (http://localhost/stafford/bower_components/angular-bootstrap-slider/slider.js:41:30)
>     at invokeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:8281:9)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7791:11)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7140:13)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7143:13)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7143:13)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7786:24)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7140:13)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7786:24) <div class="basemap-slider ng-isolate-scope" style="width: 100%" ng-model="vmBasemapSlider.sliderValue" min="vmBasemapSlider.sliderOptions.min" step="vmBasemapSlider.sliderOptions.step" max="vmBasemapSlider.sliderOptions.max" value="vmBasemapSlider.sliderOptions.value" precision="vmBasemapSlider.sliderOptions.precision" ng-change="vmBasemapSlider.changeOpacity()">(anonymous function) @ angular.js:8619(anonymous function) @ exception-handler.provider.js:51invokeLinkFn @ angular.js:8283nodeLinkFn @ angular.js:7791compositeLinkFn @ angular.js:7140compositeLinkFn @ angular.js:7143compositeLinkFn @ angular.js:7143nodeLinkFn @ angular.js:7786compositeLinkFn @ angular.js:7140nodeLinkFn @ angular.js:7786(anonymous function) @ angular.js:8021processQueue @ angular.js:13318(anonymous function) @ angular.js:13334$digest @ angular.js:14386$apply @ angular.js:14675done @ angular.js:9725completeRequest @ angular.js:9915requestLoaded @ angular.js:9856
> logger.js:20 Error: ApplicationErrorSlider is not a constructor Objectcause: "<div class="basemap-slider ng-isolate-scope" style="width: 100%" ng-model="vmBasemapSlider.sliderValue" min="vmBasemapSlider.sliderOptions.min" step="vmBasemapSlider.sliderOptions.step" max="vmBasemapSlider.sliderOptions.max" value="vmBasemapSlider.sliderOptions.value" precision="vmBasemapSlider.sliderOptions.precision" ng-change="vmBasemapSlider.changeOpacity()">"exception: TypeError: ApplicationErrorSlider is not a constructor
>     at initSlider (http://localhost/stafford/bower_components/angular-bootstrap-slider/slider.js:143:34)
>     at link (http://localhost/stafford/bower_components/angular-bootstrap-slider/slider.js:41:30)
>     at invokeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:8281:9)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7791:11)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7140:13)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7143:13)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7143:13)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7786:24)
>     at compositeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7140:13)
>     at nodeLinkFn (http://localhost/stafford/bower_components/angular/angular.js:7786:24)__proto__: Objecterror @ logger.js:20(anonymous function) @ exception-handler.provider.js:61invokeLinkFn @ angular.js:8283nodeLinkFn @ angular.js:7791compositeLinkFn @ angular.js:7140compositeLinkFn @ angular.js:7143compositeLinkFn @ angular.js:7143nodeLinkFn @ angular.js:7786compositeLinkFn @ angular.js:7140nodeLinkFn @ angular.js:7786(anonymous function) @ angular.js:8021processQueue @ angular.js:13318(anonymous function) @ angular.js:13334$digest @ angular.js:14386$apply @ angular.js:14675done @ angular.js:9725completeRequest @ angular.js:9915requestLoaded @ angular.js:9856
> angular.js:11670 [Angular - Esri] Initializing external links page

**Comment by seiyria** [comment]
Please report this [on the correct repo](https://github.com/seiyria/angular-bootstrap-slider).
